### ISSUE TITLE
do-insert-bibtex fails with error

### ISSUE THREAD

**Issue by pharos-alexandria** [cpitclaudel/biblio.el#12]
If I search for a doi, I get this error:

```Error while processing request: (error "Invalid response from server: \"\"") [2 times]```

Do you have a clue, why this happens?

**Comment by cpitclaudel** [comment]
Can you give a concrete example of a DOI that you searched for?

**Comment by pharos-alexandria** [comment]
Sorry for this late answer! In the meantime it works as it should. Thank ou for this great tool!
