### ISSUE TITLE
Feature Request: IEEE support

### ISSUE THREAD

**Issue by notuntoward** [cpitclaudel/biblio.el#16]
The IEEE journals

http://ieeexplore.ieee.org/Xplore/home.jsp

are widely used, and in addition, the Bibtex the IEEE search engine returns is often of better quality than, for example Google Scholar -- better handling of umlauts, full journal details, etc.

IEEE will also retrieve the paper abstracts, which I find to be valuable grep targets when I'm searching my oversized bibtex file for "that paper I can't quite remember but know I read sometime."

So a feature request: could you please add IEEE as a search option?

**Comment by cpitclaudel** [comment]
Sounds like a good idea. Can you help by investigating whether there is an IEEE API, and posting an example of input and output?

**Comment by ebpa** [comment]
Here's an overview page of the search parameters: http://ieeexplore.ieee.org/gateway/

That page lists several examples (GET):

1. Returns records 11-20 matching java in any metadata field, Wang in Authors, sorted on Document Title.
```
http://ieeexplore.ieee.org/gateway/ipsSearch.jsp?querytext=java&au=Wang&hc=10&rs=11&sortfield=ti&sortorder=asc 
```

There's a client library written in R that might be a useful reference as well.

**Comment by cpitclaudel** [comment]
Thanks.  It looks like the XML API was deprecated (https://github.com/ropensci/IEEER/issues/18), and apparently the new API requires applications to sign up and get an API token (which we can't keep private since this program's code source is public).  I just emailed them to ask about this:

> Hi,
>
> I'd like to add support for IEEE Xplore in biblio.el, a free ("open-source") program for browsing and retrieving bibliographic records.  See https://github.com/cpitclaudel/biblio.el for more details.
>
> I ran into an issue, however: it seems that I need an API key, and that this key should be kept private.  But the source code of my program is public, so distributing the key with the program would make the key public.
>
> What is the recommended approach in this case?
>
> Thanks.

**Comment by cpitclaudel** [comment]
I heard back, and the IEEE Xplore people were kind enough to issue an API key for biblio.el.  I'll add support at some point, but it may be a few weeks.  Please ping me if nothing happens within a month or so? Thanks!

**Comment by mgttlinger** [comment]
@cpitclaudel So did you try to implement this?

**Comment by senselessDev** [comment]
ping ;)

**Comment by tmalsburg** [comment]
Hey, I won't be able to do any serious work on helm-bibtex at least until the end of the lecture period in three weeks.  But feel free to ping  me again.  :)

**Comment by cpitclaudel** [comment]
Done, please test and report :)

**Comment by cpitclaudel** [comment]
Thanks for the ping, btw.

**Comment by mgttlinger** [comment]
Seems to work from what I can tell. Thanks for implementing that!

**Comment by cpitclaudel** [comment]
Thanks for testing!

**Comment by senselessDev** [comment]
Working here as well, thank you very much!
