### ISSUE TITLE
Port to something but elisp/emacs

### ISSUE THREAD

**Issue by danr** [cpitclaudel/biblio.el#18]
It would be nice to be able to be able to use the functionality from this package without emacs as a dependency. 

(related: Are there other known tools like this?)

**Comment by cpitclaudel** [comment]
That might be nice, but I think the chance of this happening is pretty low :/ Unless someones steps in? This package relies pretty heavily on Emacs/Elisp facilities.

(Not sure; the closest might be Google Scholar's search UI)

**Comment by danr** [comment]
Would it be possible to have some core of this library that is both valid elisp and some stand-alone lisp implementation? That would open the possibility to make a command line tool that takes a query and returns the result on stdout (perhaps simply as an sexpr).

**Comment by cpitclaudel** [comment]
Possibly, though the API that the code uses currently are pretty emacs-specific.  Writing a compatibility layer would clutter the code a lot.

Making a CLI in ELisp for the current code would be fairly easy, though.  For that use case, why does the language matter?

**Comment by danr** [comment]
A CLI via emacs/elisp sounds very useful. And true, for that use case it does not matter what the internal language is. :+1:

**Comment by cpitclaudel** [comment]
That makes sense / sounds feasible, but I don't expect I'll have a lots of time to put into this soon.
Feel free to give it a try :) I'm happy to provide guidance if needed.

**Comment by danr** [comment]
Np, I don't think I can either. Let's just keep this discussion as an open issue in case someone considers the same idea.

**Comment by cpitclaudel** [comment]
I'll close this since I'm not going to work on it soon, but I'll leave the discussion open for people to chime in.
