### ISSUE TITLE
Add a header line in results buffer showing the available actions

### ISSUE THREAD

**Issue by tmalsburg** [cpitclaudel/biblio.el#2]
Similar to the header line in org-capture buffers.  This increases the discoverability of the the actions.

**Comment by cpitclaudel** [comment]
Neat suggestion! What do you think of this?

![screenshot from 2016-04-04 12 28 12](https://cloud.githubusercontent.com/assets/8181630/14246699/b9c69fd4-fa60-11e5-9bdb-15f6463d1b4e.png)

**Comment by cpitclaudel** [comment]
Also, did you see the help screen that `h` pops up? It's not the usual `describe-mode` :)

**Comment by tmalsburg** [comment]
Not sure if there are conventions for the formatting of the header line but this looks really good.  I missed the message in the mini-buffer the first couple of times.  I think a header line (`header-line-format`) is a more standard solution to make the user aware of important key-bindings.

**Comment by cpitclaudel** [comment]
Pushed :)

**Comment by tmalsburg** [comment]
Nice, thank you!

**Comment by tmalsburg** [comment]
Just pushed support for biblio.el in helm-bibtex.  See the added fallback options.  Suggestions welcome.

**Comment by cpitclaudel** [comment]
Awesome; belated thanks :)
