### ISSUE TITLE
release 0.2

### ISSUE THREAD

**Issue by pmeckoni** [cpitclaudel/biblio.el#21]
i'm currently trying to install org-ref from melpa stable which needs biblio 0.2 
melpa stable uses your release 0.1 (possibly march 2016). and your last commit seems to be for october 2016.
can you release another version so that dependencies for stable are resolved.

**Comment by cpitclaudel** [comment]
Ouch, sorry. Will do today.

**Comment by cpitclaudel** [comment]
Done, I think.
