### ISSUE TITLE
Bibsonomy backend

### ISSUE THREAD

**Issue by andreasjansson** [cpitclaudel/biblio.el#26]
Thanks for biblio.el, it's a great time saver!

I wrote a backend for [Bibsonomy](https://www.bibsonomy.org/): https://github.com/andreasjansson/biblio-bibsonomy.el. I think I got the backend hooks right, but an extra pair of eyes probably wouldn't hurt?

There's a PR open to add it to MELPA [here](https://github.com/melpa/melpa/pull/5893).

**Comment by cpitclaudel** [comment]
Hey, this looks great :) I read through the code and left two comments.
Great work!

**Comment by andreasjansson** [comment]
Thanks for the review! I fixed those two issues.

Will update here when it's merged into MELPA.

**Comment by andreasjansson** [comment]
Merged into MELPA now.

**Comment by cpitclaudel** [comment]
Yay! :)
