### ISSUE TITLE
Support crossref API "politely" for better service

### ISSUE THREAD

**Issue by leezu** [cpitclaudel/biblio.el#27]
> As of September 18th 2017 any API queries that use HTTPS and have appropriate contact information will be directed to a special pool of API machines that are reserved for polite users.

> How does it work? Simple. You can do one of two things to get directed to the "polite pool":
> 
> Include a "mailto" parameter in your query. For example:
> 
> https://api.crossref.org/works?filter=has-full-text:true&mailto=GroovyBib@example.org
> 
> Include a "mailto:" in your User-Agent header. For example:
> 
> GroovyBib/1.1 (https://example.org/GroovyBib/; mailto:GroovyBib@example.org) BasedOnFunkyLib/1.4.
> 
> Note that this only works if you query the API using HTTPS. You really should be doing that anyway (wags finger).

https://github.com/CrossRef/rest-api-doc#good-manners--more-reliable-service

**Comment by cpitclaudel** [comment]
Thanks for the note. I will look into this.

**Comment by cpitclaudel** [comment]
I had a look; thanks again for the pointer.  What do you suggest to implement? I could put my email, but that wouldn't help the CrossRef authors limit abuse, would it? If someone used biblio.el to spam the API, I wouldn't be able to help much at all.

**Comment by leezu** [comment]
How about defaulting to the current, unpolite handling but adding a configuration option for users to specify the mailto parameter and documenting it in the Readme?

**Comment by cpitclaudel** [comment]
Sounds reasonable. Thanks! I'll do it soon.

**Comment by m4lvin** [comment]
It seems the queries are still done via HTTP and not HTTPS.
Could you also change `http://api.crossref.org` to `https://api.crossref.org`?

(And many thanks for this great package!)

**Comment by cpitclaudel** [comment]
Done, thanks for the suggestion.
