### ISSUE TITLE
Open bib file before inserting entries

### ISSUE THREAD

**Issue by jagrg** [cpitclaudel/biblio.el#4]
I would like to be ale to insert entries from any file (not just from the bib file). For example, if I'm drafting a paper and call `biblio-lookup`, I would like biblio to open my bib file and insert the selected entry on the bottom of that file, with one empty line between entries, and possibly in the same window of the biblio results. Once we hit `i`, I don't think we need the biblio window open.

**Comment by cpitclaudel** [comment]
> Once we hit i, I don't think we need the biblio window open.

Does pressing `I` work?

**Comment by jagrg** [comment]
Yes. I missed the capital `i`.
