### ISSUE TITLE
Add other bindings for previous and next

### ISSUE THREAD

**Issue by mlemerre** [cpitclaudel/biblio.el#41]
Hi,

I really like biblio. Something that is bugging me is the binding for next and previous is C-n/C-p, and my muscle memory could not find it (it is not something common in packages I use). I think n/p would be a good fit in this read-only buffer (like in dired,magit); M-n and M-p could be used too (if you dont' plan on using them).

I did not submit a patch as it is trivial. I can do it in my configuration, but I think others would benefit from the change.

`(define-key biblio-selection-mode-map (kbd "n") 'biblio--selection-next)`
`(define-key biblio-selection-mode-map (kbd "p") 'biblio--selection-previous)`

Thanks for biblio.el!
Matthieu

**Comment by cpitclaudel** [comment]
Ouch, sorry for the delay.  This is a great idea.  Done.
