### ISSUE TITLE
Error while processing request: (file-missing "Cannot open load file" "tex-buf")

### ISSUE THREAD

**Issue by basille** [cpitclaudel/biblio.el#57]
Hi!

On a new install (Ubuntu 22.04, Emacs 27.1), I'm having issues inserting references in my BibTeX file, for instance with `doi-insert-bibtex` or through an initial lookup through CrossRef. Examples:

```
M-X doi-insert-bibtex RET https://doi.org/10.1145/2676726.2677006
```

results in:
```
Fetching https://doi.org/10.1145/2676726.2677006
Contacting host: doi.org:443
Error while processing request: (file-missing "Cannot open load file" "Aucun fichier ou dossier de ce type" "tex-buf")
```

or
```
M-x crossref-lookup RET fiat deductive delaware RET i
```

results in:
```
Fetching https://api.crossref.org/works?query=fiat%20deductive%20delaware
Contacting host: api.crossref.org:443
Tip: learn to browse results with ‘h’
Fetching https://doi.org/10.1145/2775051.2677006
Contacting host: doi.org:443
Error while processing request: (file-missing "Cannot open load file" "Aucun fichier ou dossier de ce type" "tex-buf")
```

I have a rather complex [Emacs config](https://github.com/basille/.emacs.d/blob/master/init.org#bibtex=), so it might be related to some other package. Happy to help debug this one, but I don't really know where to start. Thanks for your help!

---
- Specific Emacs version: 
```
GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0)
 of 2022-01-24, modified by Debian
```
- Specific `biblio.el` version:
```
  biblio             20210418.406  dependency            Browse and import bibliographic references from CrossRef, arXiv, DBLP, HAL, Dissemin, and doi.org
  biblio-core        20210418.406  dependency            A framework for looking up and displaying bibliographic entries
```

**Comment by cpitclaudel** [comment]
`tex-buf` is a library provided by auctex; maybe try installing that package?  It looks like you have a hook somewhere that requires it, but I won't be able to help debug your config :/

You could try M-x toggle-debug-on-error and see whether you get a backtrace; that might tell you which part of the config is the issue.

**Comment by basille** [comment]
Thanks so much @cpitclaudel for looking into it! I had `auctex`, even tried to remove it entirely and reinstall it, to no avail…

… until this morning, where everything works fine. I don't think I changed a bit between my bug report and now, so it is totally unclear why things are functional now, but not then (and weren't for a few days at least). And I didn't even use `M-x butterfly`.

I'm closing this bug report, which is so completely random now.
