### ISSUE TITLE
Using citar to display results of web search

### ISSUE THREAD

**Issue by ramos** [cpitclaudel/biblio.el#61]
Hello,

Would it be possible to use citar functions to parse a dedicated buffer? I have my own elisp functions that make dedicated searches in online databases. I would like to display the results using citar (with completion, etc...)

Is there any funciton that accepts a buffer as argument, parses it, and uses this as completion candidates?

Many thanks for the awesome citar!

**Comment by cpitclaudel** [comment]
This issue should probably be opened in the citar repo?
