### ISSUE TITLE
Article download does not work for articles found via DBLP

### ISSUE THREAD

**Issue by lecopivo** [cpitclaudel/biblio.el#7]
When I find and article via DBLP and I want to download it though dissemin, I do `x RET` on selected article. I get an error `Dissemin needs a DOI, but this record does not contain one`. But the bibtex entry for that article contains valid doi.

**Comment by cpitclaudel** [comment]
Yup, and that's really frustrating, too.

Here's the issue: in the records that DBLP returns, there is indeed no DOI; there is no BibTeX either. When you ask for the BibTeX, however, biblio queries the DBLP server for it, and it comes back with a DOI. That's why the BibTeX itself contains a DOI; but the record that is originally fetched from DBLP's servers does not include one.

Ideally, this could be fixed by Dissemin enhancing their API to allow lookups by DBLP ids; I posted code to that effect at https://github.com/dissemin/dissemin/issues/208. When it gets merged, things will work smoothly.

Does this help?

**Comment by lecopivo** [comment]
I see, there is really no doi in the DBLP querry.

Thank you, It kind of helped me to understand how biblio works, since I'm trying to write my own backend.

**Comment by cpitclaudel** [comment]
Great :) Let me know if you need help with defining a backend! If anything is unclear, we should treat it as a documentation bug in `biblio.el`.

I'll leave this open until we get better support from dissemin. (ping @threonorm? :smile:)

**Comment by nelson-liu** [comment]
I'm also getting this error when trying to download from arxiv -- is this intended?

**Comment by cpitclaudel** [comment]
@nelson-liu yes; not all entries on ArXiV have a DOI. Why do you want to look up arXiv entries on Dissemin?

**Comment by nelson-liu** [comment]
@cpitclaudel well more broadly, I want to be able to download arxiv papers from emacs. Is there any way to do this without dissemin?

Here's what i'm trying to do right now:
1. run `biblio-arxiv-lookup`
2. select the entry i want to insert bibtex for (for the current file)
3. (ideally, download the file)

I can do steps 1 and 2 right now, but when i hit `x` for `Extended action` to download, it doesn't work. Is there anyway to make the above possible?

Thanks so much!

**Comment by cpitclaudel** [comment]
@nelson-liu Sorry for the delay. I'm not sure why this fell off my radar :/

This should be easy to add for arXiv and HAL, since these two sources provide a download link. I've pushed an update that lets you open the PDF directly using `C-RET` for these two backends; it will be on MELPA in a few hours.

Can you try it out? Some questions:

* Does this work for you?
* What do you think of `C-return` as the binding for that action?
* Do you just want to open the PDF in your browser, or would you like a way to download it directly (such a thing could be implemented as a separate extended action)?

**Comment by nelson-liu** [comment]
Thanks for the response @cpitclaudel! I'll try it out when it's on MELPA and get back to you. C-return seems like a reasonable binding to me, but I'd also prefer if there was a way for me to download the file directly to my system from emacs.

**Comment by cpitclaudel** [comment]
@nelson-liu Ok, neat. I think we could add a `download` extended action.
Do you think it should prompt you for a file path to save under every time, or should it just download to your `Downloads` folder (or a user-customizable folder?)

**Comment by nelson-liu** [comment]
hmm, good question. I'd personally prefer the latter option (user-customizable folder), but i could see the use / flexibility of prompting for a file path to save under every time. As a result, maybe the former option (prompt every time) would be better?

**Comment by nelson-liu** [comment]
@cpitclaudel sorry for the delay on this, but I just downloaded your latest update and the functionality for `C-ret` opening the pdf in the browser works well here. Thanks so much!

**Comment by cpitclaudel** [comment]
Brilliant, thanks for testing! I'll add a download shortcut as an extended action soon.

**Comment by cpitclaudel** [comment]
Ok, should be part of the next MELPA build :) You can press `x` to pop up extended actions, and there should be a `download` entry there (currently only working with HAL and arXiv)

**Comment by cpitclaudel** [comment]
Happy to hear comments about improving the experience, btw :)

**Comment by nelson-liu** [comment]
great, seems to work quite well from what i see :) thanks so much! would it be possible by any chance to have something that we were talking about earlier, i.e. auto-download to a folder? I'd imagine you could do something like check a variable (that is nil by default), and download to the path in that variable if it is non-nil. Thus, users that wanted this functionality specifically could just set that in their init. I don't quite have a sense of how difficult that would be, however.

**Comment by cpitclaudel** [comment]
@nelson-liu I think this is essentially what will happen with my current implementation; more precisely, you'll get a prompt for a file name with a default filled in based on `biblio-download-directory` (which is a customizable variable). If you're satisfied with the default, you'll be able to just press `RET` directly.

Let's try this out, and if that extra `RET` is too much, we can add an option to remove the prompt :)

**Comment by nelson-liu** [comment]
@cpitclaudel Ah, sorry for missing that. I just tried it out, and it works great. 

i actually prefer the extra `RET`! Having the option to choose a custom directory easily whenever I want is well worth the extra keypress :)

 This feature is surely going to become a staple of my note-taking workflow; lots of the papers that I read are on arxiv, and I previously didn't have a good way to acquire them through emacs. Thanks so much for adding this feature!

**Comment by cpitclaudel** [comment]
Brilliant, thanks very much for the suggestion!

**Comment by cpitclaudel** [comment]
I think this is all done :) ot sure why I didn't close it after implementing the suggestion ^^
