### ISSUE TITLE
Backend documentation

### ISSUE THREAD

**Issue by lecopivo** [cpitclaudel/biblio.el#8]
I'll post here my struggles with implementing new backend.

First question:
Documentation for `biblio-backends` says:

    ‘parse-buffer’: (on argument, BUFFER) Parse the contents of
    BUFFER (current at the time of the call) and return a list of
    results.

Is there really `on argument`? What does `on` mean? If it is typo and should be `one` then for example `biblio-arxiv--parse-search-results` does not take any argument.

I guess that It calls the function with `BUFFER` as current buffer.

And what should be the format of the output list?

**Comment by cpitclaudel** [comment]
Yuck yuck yuck, you're absolutely right. Fixing it right now.

**Comment by cpitclaudel** [comment]
Let me know if this update helps :)

**Comment by lecopivo** [comment]
Sweet, It makes perfect sense now!

**Comment by cpitclaudel** [comment]
Yay! Feel free to open more issues; writing good documentation is so much easier with pointers to unclear parts :)
