### ISSUE TITLE
feature request: add year to arxiv bibtex

### ISSUE THREAD

**Issue by nelson-liu** [cpitclaudel/biblio.el#9]
Hi! Would it be possible to add the year to the inserted bibtex from an arvix lookup? Right now, it is simply `year = {nil}`.

Additionally, it seems like the title for arxiv entry of bibtex is a bit malformed. This is an example bibtex entry generated (note the title attribute):
```
@article{hillil:learn_under_phras_embed_diction,
  author       = {Felix Hill AND Kyunghyun Cho AND Anna Korhonen AND Yoshua
                  Bengio},
  title        = {{Learning to Understand Phrases by Embedding the Dictionary}},
  year         = {2016},
  archiveprefix= {arXiv},
  eprint       = {1504.00548v4},
  primaryclass = {cs.CL}
}
```
I'm not sure if this is intended, but I don't often see double braces used?

Thanks!

**Comment by cpitclaudel** [comment]
I'll look into this. I'm in deadline mode ATM, so ping me if you haven't heard back in one week? Thanks!

**Comment by nelson-liu** [comment]
sure, no rush at all. goodluck!

**Comment by nelson-liu** [comment]
Thanks!
